### ISSUE TITLE
Main site Dashboard menu: issues scrolling to the bottom

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#315] opened 2020-11-11 12:52 UTC
Hi Boone, 

This has been an issue since the beginning. I think it was raised on Basecamp but I can't find a ticket for it. It's back on our radar again since it was recently mentioned by a user in the forum..  

The problem is that sometimes it's difficult to scroll all the way to the bottom of the menu in the main site Dashboard, making it difficult to access things at the bottom, like Users, Tools, Settings, etc, because it gets stuck at a certain point above those menu items. Then, sometimes it also gets stuck so that the very top Dashboard menu item is not accessible. 

Sometimes I can scroll without a problem, and sometimes I can "unstick" it by going to the CBOX OpenLab section of the Dashboard, and then scrolling to the bottom.

Thanks!

![DashboardStickiness](https://user-images.githubusercontent.com/7189824/98813621-79f3a300-23f2-11eb-9f6d-97f350d9f19d.gif)

**Comment by boonebgorges** [comment] 2020-11-11 17:21
Thanks, @bree-z . I believe this is a duplicate of #175. Can you confirm?

**Comment by bree-z** [comment] 2020-11-11 19:23
Oh, yes, it is a duplicate. Sorry about that!

**Comment by r-a-y** [comment] 2020-11-16 21:26
Closing as a duplicate of #175.

**Closed by r-a-y** 2020-11-16 21:26 UTC
Labels: OpenLab
