### ISSUE TITLE
Filter plug-in

### ISSUE THREAD

**Issue by github-trh** [cuny-academic-commons/commons-in-a-box#116] opened 2017-01-09 17:23 UTC
@boonebgorges Can you tell me what Filter you all use on the CUNY members directory page?  Thanks for the help!

**Comment by boonebgorges** [comment] 2017-01-09 20:42
Hi @github-trh - Sure. We're using a slightly modified version of https://github.com/boonebgorges/bp-better-directories. (Modifed to include some filter types that we add via plugin.) Be sure to use the 1.0.x branch: https://github.com/boonebgorges/bp-better-directories/tree/1.0.x

**Comment by github-trh** [comment] 2017-01-09 22:14
Thanks @boonebgorges!!  I downloaded 1.0x (your link) and dropped it in my plugins.  I went to Buddypress/BP BD and selected fields and saved.  I'm not a novice programmer or anything and was thinking this might be a widget I simply drop in my Members Sidebar.  Is that not the case?  I'm using the Commons in a Box Child theme.  Thanks for the help, I would love to get this working as it is much cleaner than any other plugin I have found thus far.

**Comment by boonebgorges** [comment] 2017-01-10 03:51
Oh right, it might not work out of the box with newer themes. (It tries to inject itself dynamically into your template, but the technique was designed for older themes.) 

Add this markup and action to your directory template https://github.com/boonebgorges/bp-better-directories/blob/1.0.x/templates/members/index.php#L41 and the plugin ought to hook itself up.

**Comment by github-trh** [comment] 2017-01-10 14:04
@boonebgorges That appears to be the same index.php in the ...\plugins\bp-better-directories-1.0.x\templates\members folder but I copied/pasted the content and saved just in case it was not.  Same result unfortunately, with no evidence on the user end that this plugin is in place.  Here is what appears on the backend:
![image](https://cloud.githubusercontent.com/assets/15528543/21808972/4d34b6e8-d70b-11e6-9e37-0d99c1aa5dc7.png)

**Comment by boonebgorges** [comment] 2017-01-10 15:04
The back-end settings look fine. You should modify your active theme so 
that the members directory template has the markup and do_action() call 
that I linked too - that's how the plugin puts the content into the page.

**Comment by github-trh** [comment] 2017-01-10 19:15
@boonebgorges - You'll have to forgive me, I'm still in learning mode here.  For the past several hours I have tried to copy/paste all or various parts of the linked index.php file above into this index.php:

![image](https://cloud.githubusercontent.com/assets/15528543/21820783/bd6066e4-d736-11e6-8670-8cf80a5cba90.png)

...with no success.  Maybe I'm simply not following your directions very well.

**Comment by boonebgorges** [comment] 2017-01-10 19:20
Yes, that looks like the right file. I'm afraid I don't know what might be wrong. Here's where the plugin should be generating markup: https://github.com/boonebgorges/bp-better-directories/blob/1.0.x/bpbd.php#L174 This is where I'd start the debugging process.

**Comment by github-trh** [comment] 2017-01-10 23:18
@boonebgorges 

"...._The back-end settings look fine. You should modify your active theme so that the members directory template has the markup and do_action() call that I linked too - that's how the plugin puts the content into the page_."

Back to your original instructions...what exact portion of the index.php do I copy and where do I place it exactly in the theme's member's index.php?  Thank you for your patience!

**Comment by boonebgorges** [comment] 2017-01-10 23:36
Try switching to the 0.9.x branch and see if it works. It looks like 
1.0.x is a Backbone-based rewrite that may not be fully ready.

**Comment by github-trh** [comment] 2017-01-11 03:51
Hey, I did just that and now it shows up in the main body above the Members Directory!  I'm just super-excited it showed up!  Ok, now it unfortunately is not working when attempting to filter (does nothing when hitting Submit) and when trying to "Clear" or "Clear All", it doesn't clear, but just sends me to the top of the page.  As far as locating it in the sidebar instead of the main body similar to CUNY, I imagine I can just copy/paste the inner HTML into a widget.

**Comment by r-a-y** [comment] 2017-03-06 20:50
I'm closing this issue as this is not related to CBOX and to clear the Issues list, but feel free to continue commenting if you need to, @github-trh.

**Closed by r-a-y** 2017-03-06 20:50 UTC
