### ISSUE TITLE
Group Calendar Errors

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#163] opened 2018-12-16 23:47 UTC
A user [has reported](https://commonsinabox.org/groups/openlab-help-support/forum/topic/event-calendar-issues/) some issues using the group calendar:

1. On the events entry page I am getting a warning as shown in the [screen shot attached](https://commonsinabox.org/wp-content/uploads/2018/12/admin_panel_event_warning.png), and it does not seem to save location information. 

2. Then on the Group calendar page there are some console errors. ([screen cap also attached](https://commonsinabox.org/wp-content/uploads/2018/12/group_calendar_console_errors.png))

He also notes that both may be related to mapping providers.

I'm not able to reproduce the issues exactly, but I am noticing some strange behavior on openlabdev.commonsinabox.org:

1. On the 'All events' page (e.g. https://openlabdev.commonsinabox.org/groups/december-course/events/), the calendar doesn't load.  I just see a spinning circle with the text "Loading..." and don't see anything in the JS console.  

2. When I add a new event, I can add a title, but can't click in the Event Description box to add a description.  When I click in the Start and End Date/Time fields, I don't get the calendar date picker, but I'm able to manually add dates.  When I add a venue, the map doesn't appear.  And, the site-wide footer doesn't load.  I see some Google Maps errors in the console.  

Thanks!

![calendar_allevents](https://user-images.githubusercontent.com/7189824/50060489-ced50300-0162-11e9-8364-0952418152fb.png)

![calendarnewevent](https://user-images.githubusercontent.com/7189824/50060490-ced50300-0162-11e9-9bc6-e9bdb913825f.png)

![calendarnomaporfooter](https://user-images.githubusercontent.com/7189824/50060491-ced50300-0162-11e9-970b-23ad041ed688.png)

**Comment by r-a-y** [comment] 2019-01-16 12:06
> On the 'All events' page (e.g. https://openlabdev.commonsinabox.org/groups/december-course/events/), the calendar doesn't load. I just see a spinning circle with the text "Loading..." and don't see anything in the JS console.

I was able to duplicate this bug.

We are removing the event category functionality in `openlab-theme`:
https://github.com/cuny-academic-commons/openlab-theme/blob/master/lib/plugin-mods/calendar-control.php#L239

The problem is the core Event Organiser plugin doesn't do a proper check to see if the event category taxonomy still exists or not.  This causes a problem with the JSON response generation being invalid.  I've opened a pull request with a fix here - https://github.com/stephenharris/Event-Organiser/pull/455

In the meantime, there might be a way to workaround this problem ourselves, but will require a bit more research.  CC @boonebgorges.

----

> On the events entry page I am getting a warning as shown in the screen shot attached, and it does not seem to save location information.

Can you look into this, @boonebgorges ?  I don't have a Google Maps API key to test this functionality at the moment.

----

I wasn't able to duplicate the other problems.

**Comment by boonebgorges** [comment] 2019-01-16 16:09
> (Maybe reinstate the event category taxonomy, but hide the field via a CSS hack?)

This is inelegant but should be fast and effective until the upstream improvement is in place.

>  Can you look into this, @boonebgorges ? I don't have a Google Maps API key to test this functionality at the moment.

I've added it to my queue. Thanks!

**Comment by r-a-y** [comment] 2019-01-29 09:59
All issues should be fixed in the `openlab-theme` repo.  See referenced commits above if you are interested in testing before release.

Closing, but feel free to reopen if you are still encountering problems

**Comment by bree-z** [comment] 2019-02-04 00:03
I'm still seeing the same issues on openlabdev.commonsinabox.org.  E.g., testing in this group: https://openlabdev.commonsinabox.org/groups/writing-about-winter/ I still see the following:

* On the 'All events' page (e.g. hhttps://openlabdev.commonsinabox.org/groups/writing-about-winter/events/), the calendar doesn't load. I just see a spinning circle with the text "Loading..." and don't see anything in the JS console.
* When I add a new event, I can add a title, but can't click in the Event Description box to add a description. When I click in the Start and End Date/Time fields, I don't get the calendar date picker, but I'm able to manually add dates. When I add a venue, the map doesn't appear. And, the site-wide footer doesn't load. I see some Google Maps errors in the console.
* Additionally, when I click Event Description box, I can't see my cursor, and if I add text, it appears to be white (see screenshot with text highlighted).

Thanks!

<img width="943" alt="calendarloading" src="https://user-images.githubusercontent.com/7189824/52184807-3fed7a00-27e6-11e9-8c84-3709b72669d8.png">

![calendarmissingdatepicker](https://user-images.githubusercontent.com/7189824/52184808-3fed7a00-27e6-11e9-8ff6-fcbfee798765.png)

![calendarmissingfooter](https://user-images.githubusercontent.com/7189824/52184809-3fed7a00-27e6-11e9-8c51-bf8c36eceec4.png)

![calendarwhitetext](https://user-images.githubusercontent.com/7189824/52184810-3fed7a00-27e6-11e9-8c80-0b78398f2043.png)

**Comment by bree-z** [comment] 2019-02-04 19:24
Thanks, @r-a-y !  That appeared to be the issue.  

Just a quick question though: what is the intended functionality?  Should I be seeing a map and/or address?  I can't see an address even when I added one, and I also don't see a map displayed anywhere.  

This appears to be how events are working on the OpenLab, but on the Commons it looks like a map displays for events with an address, although it looks like this map isn't showing the correct location: https://commons.gc.cuny.edu/events/event/hip-hop-pedagogy/  

See, for example: https://openlabdev.commonsinabox.org/groups/writing-about-winter/events/something-at-city-tech/

I was testing with Chrome:

<img width="896" alt="screen shot 2019-02-04 at 2 18 14 pm" src="https://user-images.githubusercontent.com/7189824/52231410-dcb42400-2887-11e9-8697-47de276abab1.png">

<img width="1201" alt="screen shot 2019-02-04 at 2 18 35 pm" src="https://user-images.githubusercontent.com/7189824/52231411-dcb42400-2887-11e9-92b8-5ca32ffeb50a.png">

**Comment by r-a-y** [comment] 2019-02-04 19:41
@bree-z - Looks like there is a bug with our custom maps functionality for OpenLab.

My local install is using Event Organiser 3.6.5, while the dev site is using Event Organiser 3.7.4.  Something changed in EO 3.7.4 that needs addressing.

For @boonebgorges when he gets back:

```
Uncaught TypeError: eovenue.maps.venuemap.map.addListener is not a function
    at Object.venueMapControl (/wp-content/themes/openlab-theme/js/utility.js?ver=1.1.0-1540822223687:157)
    at utility.js?ver=1.1.0-1540822223687:681
    at dispatch (jquery.js?ver=1.12.4:3)
    at r.handle (jquery.js?ver=1.12.4:3)
```

**Comment by boonebgorges** [comment] 2019-02-05 23:03
I believe I've resolved the `addListener` issue.

**Comment by boonebgorges** [comment] 2019-02-08 02:41
Is a map *supposed* to show up here? I don't see any evidence in the template files that suggests that this is intended behavior. Does it on the OpenLab? @bree-z

**Comment by bree-z** [comment] 2019-02-08 17:33
Sorry, Boone.  Maybe the map isn't supposed to appear on this page.  It also doesn't appear on the OpenLab but I thought that was a bug as well.  I guess I wasn't sure the point of including the map is if it doesn't show up on the event details page.  :)

Apologies if I've misunderstood.  If so, I think we can close this ticket.  And perhaps it's worth considering for a future release?  

Thanks!

**Comment by boonebgorges** [comment] 2019-02-08 19:00
Yup, definitely worth considering, either here or on the OpenLab. See #176.

Thanks, Bree!

**Closed by boonebgorges** 2019-02-08 19:00 UTC
